### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by pakair** [mattymcfatty/HoneyPi#14]
Installed your script, at the very end, it pops this message ... 

ok, now reboot and you should be good to go. Then, go portscan this honeyPi from another machine and see if you get an alert!
```
pi@honey:~/HoneyPi-master $ 2020-03-04 14:17:16: Starting up honeypot python program...
Traceback (most recent call last):
  File "/root/honeyPi/mattshoneypot.py", line 50, in <module>
    reactor.listenTCP(5900, FakeVNC, interface = interface)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 1363, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on 0.0.0.0:5900: [Errno 98] Address already in use.

```

**Comment by foomip** [comment]
@pakair you probably have another service (probably VNC server) running on that port already. Stop the VNC service and then try again.

**Comment by pakair** [comment]
that was it, thank you.
