### ISSUE TITLE
Couldn't Listen on 0.0.0.0:5900 Address already in use

### ISSUE THREAD

**Issue by michael5280** [mattymcfatty/HoneyPi#3]
Matt,

Getting error similar to Robert's previously.  Any help will be greatly appreciated.

/HoneyPi-master $ 2018-09-22 16:30:53: Starting up honeypot python program...
Traceback (most recent call last):
  File "/root/honeyPi/mattshoneypot.py", line 50, in <module>
    reactor.listenTCP(5900, FakeVNC, interface = interface)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 495, in listenTCP
    p.startListening()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 979, in startListening
    raise CannotListenError(self.interface, self.port, le)
twisted.internet.error.CannotListenError: Couldn't listen on 0.0.0.0:5900: [Errno 98] Address already in use.

**Comment by r00tb3** [comment]
I'm facing this problem I've chosen to blink the LED instead of email.

Tried everything facing the same issue.

**Comment by Rizqillah** [comment]
I think you should disble vnc on 'raspi-config'
